### ISSUE TITLE
Bug: パッチアップデートに対してもリリースが作成されてしまう

### ISSUE THREAD

**Issue by kokoichi206** [kokoichi206/count-down-timer#37]
[ci のアウトプットはきちんと false を指している](https://github.com/kokoichi206/count-down-timer/runs/5431370507?check_suite_focus=true#step:5:9)のに、なぜか tag 付け＋リリース作成が行われてしまっている

`if: ${{ steps.is-release-need.outputs.need }}`の部分が、うまく `false`を判定してくれてない？

**Comment by kokoichi206** [comment]
リリース作成条件の部分に関しては改善されたっぽい

https://github.com/kokoichi206/count-down-timer/runs/5438639908?check_suite_focus=true

**Comment by kokoichi206** [comment]
kdoc のキャッシュ関係でこけている
ci に関してはここで直し切った方がいいと判断したため修正を行う

**Comment by kokoichi206** [comment]
kdoc のキャッシュを行っている step

``` yaml
- name: Cache for later upload
  uses: actions/cache@v2
  with:
    path: |
      ./kdoc
    key: ${{ runner.os }}-kdoc-${{ hashFiles('./kdoc/*') }}
    restore-keys: |
      ${{ runner.os }}-kdoc-
```

license も同様のコードでキャッシュを作成している

### 問題点？
キャッシュが見つかった場合には復元をおこなっているが、その辺？


### 解決策
データ量としては大したことないので、毎回値の変わる`app/build.gradle`ファイルなどを使って、新規の key でキャッシュを作る。
