### ISSUE TITLE
linter の導入

### ISSUE THREAD

**Issue by kokoichi206** [kokoichi206/count-down-timer#44]
ktlint なるものがあるらしいので、その導入 + ci への導入を行う

- [ktling (github)](https://github.com/pinterest/ktlint)
- [参考にしたサイト](https://kyamashiro.hateblo.jp/entry/2020/04/26/164444)

**Comment by kokoichi206** [comment]
ktlint なるものがあるらしいので、その導入 + ci への導入を行う

``` yml
ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: install danger
        run: |
          gem install bundler
          bundle install
      - name: run ktlint
        run: ./gradlew ktlint

      - name: run danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: danger
```
